language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/vue/node_modules

jobs:
  include:
    - stage: Precache
      script: yarn install --frozen-lockfile

    - stage: Build
      script:
        - cd packages/vue
        - yarn lint
        - yarn build

    - stage: Test
      script:
        - cd packages/vue
        - yarn test:unit
