language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/vue/node_modules

script:
  - yarn

jobs:
  include:
    - stage: Build
    - script:
        - cd packages/vue
        - yarn lint
        - yarn build

    - stage: Tests
    - scripts: 
      - cd packages/vue
      - yarn test:unit
      name: "Unit Tests"
