name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cache:
    name: Create cache for all steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: NOT_GENERATE_ICON=true && yarn --immutable

  commit-lint:
    name: Validate PR Title (conventional-commit)
    needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: NOT_GENERATE_ICON=true && yarn --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0

  lint:
    name: Lint
    needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run linters
        run: yarn lint

  build:
    name: Build Nuxt, Next, Docs
    needs: [cache, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run build
        run: yarn build

  build-release:
    name: Build packages for release
    needs: [cache, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run build
        run: yarn build:release

  cypress-vue:
    name: Run cypress tests(Vue)
    needs: [cache, lint]
    runs-on: ubuntu-latest
    # permissions:
    #   pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          command: yarn test:ci:vue

      # - name: Run nyc report generation
      #   id: code_coverage
      #   run: |
      #     CoverageOutput=$(cd apps/preview/vue; yarn display-coverage)
      #     CoverageOutput="$(sed 1d <<<"$CoverageOutput")"
      #     CoverageOutput="${CoverageOutput//'%'/'%25'}"
      #     CoverageOutput="${CoverageOutput//$'\n'/'%0A'}"
      #     CoverageOutput="${CoverageOutput//$'\r'/'%0D'}"
      #     echo "::set-output name=coverage::$CoverageOutput"

      # - name: Add codecoverage comments
      #   uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      #   with:
      #     message: |
      #       <details><summary>Code coverage report for <b>Vue</b></summary>

      #       ${{ steps.code_coverage.outputs.coverage }}

      #       </details>

  cypress-react:
    name: Run cypress tests(react)
    needs: [cache, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          command: yarn test:ci:react
