name: Generate changelog
on:
  release:
    types: [created, edited]

  push: 
    branches:
        - master
        - develop    

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        REPO_NAME: 'vuestorefront/sfui2'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'shared/CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update changelog notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,chore:Chore,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
